### ISSUE TITLE
release的时候报错

### ISSUE THREAD

**Issue by treblam** [fex-team/receiver#2]
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: socket hang up
    at createHangUpError (_http_client.js:215:15)
    at Socket.socketOnEnd (_http_client.js:300:23)
    at Socket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

**Comment by liuhuapiaoyuan** [comment]
同样报错。。。没人搭理一下么

**Comment by fouber** [comment]
接收端有防火墙设置吧。。。

**Comment by treblam** [comment]
我的问题找到了，是因为项目中有中文命名的文件导致的，把中文命名的文件排除掉就ok了

**Comment by oxUnd** [comment]
我试试，不应该中文名字导致系统跪了。

**Comment by DeyuanTan** [comment]
遇到同样的问题，应该是中文文件名的原因，不知这个问题解决了没有
![image](https://cloud.githubusercontent.com/assets/8966624/10386970/6ef64674-6e8f-11e5-89c3-441ee2943520.png)
下一个上传的文件是
![image](https://cloud.githubusercontent.com/assets/8966624/10386985/8ed8037e-6e8f-11e5-8be7-9b7dc15bbe1f.png)
求解救！

**Comment by wangzhiwei1888** [comment]
同样问题出现，我用的 是 centos 没有中文文件。

**Comment by xjchenhao** [comment]
额 果然是中文的问题. 可以了 3q,很方便~

**Comment by parkyang** [comment]
这个问题，该项目是否解决啊？也不给个说明？中文文件名导致该异常，除了更改为英文文件名，有其他解决方案吗？
我使用的环境：windows 7、node#v4.4.4

**Comment by oxUnd** [comment]
这个问题确定不是 nodejs 自己的？
