### ISSUE TITLE
推送图片到远端服务器报503错

### ISSUE THREAD

**Issue by shekobe** [fex-team/receiver#6]
/root/node-v4.2.2-linux-x64/lib/node_modules/fis3/node_modules/fis3-deploy-http-push/index.js:54 throw new Error(error); ^ Error: upload file [/images/hd/09/b_3.jpg] to [/usr/local/resource/static] by receiver [http://xxx.xxx.xxx.xxx:8999/receiver] error [503] at /root/node-v4.2.2-linux-x64/lib/node_modules/fis3/node_modules/fis3-deploy-http-push/index.js:54:19 at /root/node-v4.2.2-linux-x64/lib/node_modules/fis3/node_modules/fis3-deploy-http-push/index.js:15:9 at IncomingMessage. (/root/node-v4.2.2-linux-x64/lib/node_modules/fis3/lib/util.js:1246:11) at emitNone (events.js:72:20) at IncomingMessage.emit (events.js:166:7) at endReadableNT (_stream_readable.js:905:12) at doNTCallback2 (node.js:441:9) at process._tickCallback (node.js:355:17)

发送js,css，html文件就没问题，推送图片就报错了，不知道是服务器原因还是fis3原因？

**Comment by 2betop** [comment]
服务端 503 错误了，是不是做了文件上传大小限制

**Comment by shekobe** [comment]
没有限制文件大小，手动可以上传成功的。
