### ISSUE TITLE
怎么报错就是没有解决呢

### ISSUE THREAD

**Issue by zhengyange** [fex-team/receiver#8]
receiver listening *:8999
buffer.js:763
    throw new Error('Buffer.write(string, encoding, offset[, length]) ' +
    ^

Error: Buffer.write(string, encoding, offset[, length]) is no longer supported
    at Buffer.write (buffer.js:763:11)
    at MultipartParser.initWithBoundary (/Volumes/SOFT/GitHub/receiver/node_modules/formidable/lib/multipart_parser.js:61:17)
    at IncomingForm._initMultipart (/Volumes/SOFT/GitHub/receiver/node_modules/formidable/lib/incoming_form.js:325:10)
    at IncomingForm._parseContentType (/Volumes/SOFT/GitHub/receiver/node_modules/formidable/lib/incoming_form.js:268:12)
    at IncomingForm.writeHeaders (/Volumes/SOFT/GitHub/receiver/node_modules/formidable/lib/incoming_form.js:141:8)
    at IncomingForm.parse (/Volumes/SOFT/GitHub/receiver/node_modules/formidable/lib/incoming_form.js:109:8)
    at Server.<anonymous> (/Volumes/SOFT/GitHub/receiver/server.js:39:14)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:191:7)
    at HTTPParser.parserOnIncoming [as onIncoming](_http_server.js:543:12)

**Comment by oxUnd** [comment]
b316c4a46a99c005d0b2e3a5b741a0c8ae495634
