### ISSUE TITLE
无法发布啊，能否麻烦指教一下

### ISSUE THREAD

**Issue by lanxingshou** [fex-team/receiver#9]
E:\02Learning\开发框架快速入门\nodejs\FIS\FIS3\receiver-master>node server.js
receiver listening *:8999
buffer.js:735
    throw new Error('Buffer.write(string, encoding, offset[, length]) ' +
    ^

Error: Buffer.write(string, encoding, offset[, length]) is no longer supported
    at Buffer.write (buffer.js:735:11)
    at MultipartParser.initWithBoundary (E:\02Learning\开发框架快速入门\nodejs\FIS\FIS3\receiver-ma
    at IncomingForm._initMultipart (E:\02Learning\开发框架快速入门\nodejs\FIS\FIS3\receiver-master\
    at IncomingForm._parseContentType (E:\02Learning\开发框架快速入门\nodejs\FIS\FIS3\receiver-mast
    at IncomingForm.writeHeaders (E:\02Learning\开发框架快速入门\nodejs\FIS\FIS3\receiver-master\no
    at IncomingForm.parse (E:\02Learning\开发框架快速入门\nodejs\FIS\FIS3\receiver-master\node_modu
    at Server.<anonymous> (E:\02Learning\开发框架快速入门\nodejs\FIS\FIS3\receiver-master\server.js
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:191:7)
    at HTTPParser.parserOnIncoming [as onIncoming](_http_server.js:543:12)

**Comment by lanxingshou** [comment]
fis.media('prod')
  .match('*', {
  deploy: fis.plugin('http-push', {
    //receiver: 'http://192.168.0.103:8999/receiver',
   // receiver: 'http://192.168.0.119:8999/receiver',
    receiver: 'http://127.0.0.1:8999/receiver',
    //远端目录
    to: 'F:/Develop123'
  })
})

**Comment by lanxingshou** [comment]
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1008:11)
    at TCP.onread (net.js:563:26)

**Comment by areyouse7en** [comment]
一样的问题。 node 6.2.0。
npm包是 fis3-deploy-http-push。

**Comment by liuwf2012** [comment]
看报错吧，说了是函数错误

![20161025093926](https://cloud.githubusercontent.com/assets/7323242/19670152/9e1164ea-9a97-11e6-9202-6a1294c982a9.png)
![20161025094525](https://cloud.githubusercontent.com/assets/7323242/19670177/c7828d0e-9a97-11e6-92aa-21e465009f01.png)

buffer.write()在新版本的node中修改了参数顺序，把它改成最新的格式就好啦，我是成功了
![20161025094112](https://cloud.githubusercontent.com/assets/7323242/19670235/335dbc92-9a98-11e6-8237-5987fb9e63cf.png)

**Comment by web-yuzm** [comment]
我的这个文件跟你的不一样你上面这段是自己增加的？ @liuwf2012

**Comment by web-yuzm** [comment]
@liuwf2012 我的这个文件跟你的不一样你上面这段是自己增加的？

**Comment by oxUnd** [comment]
b316c4a46a99c005d0b2e3a5b741a0c8ae495634
